/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.37
 * Generated at: 2020-10-22 13:14:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class agree_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1595293922000L));
    _jspx_dependants.put("jar:file:/D:/seo_portfoilo/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/nanam/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("/member/../main/footer.jsp", Long.valueOf(1599398511067L));
    _jspx_dependants.put("/member/../main/header.jsp", Long.valueOf(1602129755239L));
    _jspx_dependants.put("jar:file:/D:/seo_portfoilo/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/nanam/WEB-INF/lib/standard.jar!/META-INF/fmt.tld", Long.valueOf(1098678690000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nanam}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/common.css\" type=\"text/css\" >\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nanam}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/header.css\" type=\"text/css\" >\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nanam}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/jquery-3.1.1.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nanam}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/jquery-ui.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nanam}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/jquery.easing.1.3.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nanam}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/prefixfree.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nanam}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/custom.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nanam}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/jquery.skitter.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nanam}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/js/jquery.skitter.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        function openWindowPop(){\r\n");
      out.write("            var url = \"/nanam/pay/point.jsp\";\r\n");
      out.write("            var name = \"popup test\";\r\n");
      out.write("            var option = \"width = 500, height = 500, top = 100, left = 200, location = no\"\r\n");
      out.write("            window.open(url, name, option);\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<!--헤더-->\r\n");
      out.write("\t<header>\r\n");
      out.write("\t\t<div id=\"headerWrap\">\r\n");
      out.write("\t\t\t<!--헤더박스-->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div id=\"headerBox\">\r\n");
      out.write("\t\t\t\t<!--로고-->\r\n");
      out.write("\t\t\t\t<a title=\"메인페이지로 이동\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nanam}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/main\"> <img\r\n");
      out.write("\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nanam}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/arr/logo2.gif\" alt=\"로고 메인페이로 이동\">\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!--//로고-->\r\n");
      out.write("\t\t\t\t<!--검색창 로그인링크-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<ul id=\"moveLoginJoin\">\r\n");
      out.write("\t\t\t\t\t");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!--//검색창 로그인링크-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!--gnb전체-->\r\n");
      out.write("\t\t\t\t<div id=\"gnbWrap\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!--토글메뉴-->\r\n");
      out.write("\t\t\t\t\t<img id=\"dropDownImg\"\r\n");
      out.write("\t\t\t\t\t\tsrc=\"./images/png-transparent-hamburger-button-computer-icons-drop-down-list-menu-angle-food-text.png\">\r\n");
      out.write("\t\t\t\t\t<!--//토글메뉴-->\r\n");
      out.write("\t\t\t\t\t<div id=\"dropDownMenu\">\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li id=\"dropFirst\">나남의책</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"dropF\"><a title=\"새로나온책\"\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"../newbooks/newbooks.html\">새로나온책 </a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"dropF\"><a title=\"스테디셀러\"\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"../steadyseller/steadyseller.html\">스테디셀러</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"dropF\"><a title=\"나남의책들\"\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"../booksofnanam/booksofnanam.html\">나남의 책들</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li id=\"dropSecond\">나남출판</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"dropS\"><a title=\"발행인 인사말\"\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"../introduce/introduce.html\">발행인 인사말</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"dropS\"><a title=\"발행인 에세이\"\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"../notice/notice.html\">발행인 에세이</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"dropS\"><a title=\"언론이 본 나남\"\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"../notice/notice.html\">언론이 본 나남</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"dropS\"><a title=\"언론이 본 나남\"\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"../notice/notice.html\">공지사항</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!--//토글메뉴-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<ul id=\"gnbBox\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<!--gnb 북-->\r\n");
      out.write("\t\t\t\t\t\t<li class=\"gnb\"><a title=\"책\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nanam}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/book/newBookFront\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"depth1\" id=\"book\">책 <span> BOOKS </span>\r\n");
      out.write("\t\t\t\t\t\t</a> <!--lnb-->\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"book menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a title=\"새로나온책\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nanam}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/book/newBookFront\">새로나온\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t책 </a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a title=\"스테디셀러\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nanam}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/book/steadyBookFront\">스테디셀러 </a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a title=\"나남의 책들\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nanam}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/book/nanamBookFront\">나남의 책들 </a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fchoose_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</div> <!--//lnb--></li>\r\n");
      out.write("\t\t\t\t\t\t<!--//gnb book-->\r\n");
      out.write("\t\t\t\t\t\t<!--gnb 출판-->\r\n");
      out.write("\t\t\t\t\t\t<li class=\"gnb\"><a title=\"출판\"\r\n");
      out.write("\t\t\t\t\t\t\thref=\"../introduce/introduce.html\" class=\"depth1\" id=\"publish\">출판\r\n");
      out.write("\t\t\t\t\t\t\t\t<span> PUBLISHING HOUSE </span>\r\n");
      out.write("\t\t\t\t\t\t</a> <!--lnb-->\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"nanam menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a title=\"발행인 인사말\" href=\"../introduce/introduce.html\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t발행인 인사말 </a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a title=\"발행인 에세이\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nanam}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/board/essayFront\">발행인\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t에세이 </a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a title=\"언론이 본 나남\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nanam}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/board/nanamFront\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t언론이 본 나남 </a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li><a title=\"공지사항\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nanam}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/board/noticeFront\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t공지사항</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fchoose_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</div> <!--//lnb--></li>\r\n");
      out.write("\t\t\t\t\t\t<!--//gnb 출판-->\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!--//gnb전체-->\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!--헤더박스-->\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!--//헤더-->\r\n");
      out.write("\t</header>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nanam}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/agree.css\" type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("  \r\n");
      out.write("\t\r\n");
      out.write("    function check() {//체크 매소드 선언\r\n");
      out.write("\r\n");
      out.write("    \tvar allChecked = false;\r\n");
      out.write("        var list = document.getElementsByName(\"list\")[0].checked;\r\n");
      out.write("        if (list) {\r\n");
      out.write("            allChecked = true;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        if (allChecked == true) { \r\n");
      out.write("            //전부 체크해줘...\r\n");
      out.write("            for (var i = 0; i < document.getElementsByName(\"list\").length; i++) {\r\n");
      out.write("                document.getElementsByName(\"list\")[i].checked = true;\r\n");
      out.write("            }\r\n");
      out.write("\t\t\r\n");
      out.write("        } else {\r\n");
      out.write("            //전체 선택이 아니라면.... 해제!!\r\n");
      out.write("            //전부 풀어줘....\r\n");
      out.write("            for (var i = 0; i < document.getElementsByName(\"list\").length; i++) {\r\n");
      out.write("                document.getElementsByName(\"list\")[i].checked = false;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("\tfunction resetPage(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//return location.href=\"../main/Index.jsp\"\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    function goNextPage(){\r\n");
      out.write("    var forceList1 = document.getElementsByName(\"list\")[1].checked;//클래스를 통한 배열 변수 선언  \r\n");
      out.write("    var forceList2 = document.getElementsByName(\"list\")[2].checked;//클래스를 통한 배열 변수 선언\r\n");
      out.write("\r\n");
      out.write("    //전체 해제 return \"\"\r\n");
      out.write("\r\n");
      out.write(" \t\r\n");
      out.write("        if ((forceList1 && forceList2)==true) {\r\n");
      out.write("        \talert(\"정보입력 페이지로 이동합니다.\")\r\n");
      out.write("           return location.href=\"/nanam/member/joinFront\";\r\n");
      out.write("        }else if((forceList1 && forceList2)==false) {\r\n");
      out.write("        \t\r\n");
      out.write("        \talert(\"필수항목은 모두 동의하셔야 합니다.\")\r\n");
      out.write("        \treturn location.href=\"#\"\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<title>약관동의</title>\r\n");
      out.write("  <!--약관동의-->\r\n");
      out.write("    <div id=\"agreeJoinWrap\">\r\n");
      out.write("        <!--inner 약관동의-->\r\n");
      out.write("        <div id=\"agreeJoinBox\">\r\n");
      out.write("            <!--basebar-->\r\n");
      out.write("            <div class=\"basebar\">\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"#\">메인</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>></li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"#\">회원가입</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>></li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"#\">약관동의</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!--//basebar-->\r\n");
      out.write("    \r\n");
      out.write("            <!--약관동의/회원가입 선택창-->\r\n");
      out.write("            <div id=\"goAgreeJoinWrap\">\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li><a title=\"로그인\" href=\"#\">약관동의 </a></li>\r\n");
      out.write("                    <li><a title=\"회원가입\" href=\"#\">회원가입</a></li>\r\n");
      out.write("            \r\n");
      out.write("                </ul>\r\n");
      out.write("            \r\n");
      out.write("                <!--//약관동의/회원가입-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <!--폼랩-->\r\n");
      out.write("                <div id=\"myFormWrap\">\r\n");
      out.write("                    <h2>\r\n");
      out.write("                        약관동의<br>\r\n");
      out.write("                        모든 체크 사항은 필수 입니다.\r\n");
      out.write("    \r\n");
      out.write("                    </h2>\r\n");
      out.write("                    <form id=\"myForm\" name=\"myForm\" method=\"get\" action=\"#\">\r\n");
      out.write("                        <!--약관동의서-->\r\n");
      out.write("                        <ul id=\"conditionsWrap\">\r\n");
      out.write("    \r\n");
      out.write("                            <!--전체동의-->\r\n");
      out.write("                            <li class=\"itemBox\">\r\n");
      out.write("                                <input type=\"checkbox\" name=\"list\" id=\"acceptAll\" onclick=\"check();\">\r\n");
      out.write("    \r\n");
      out.write("                                <label for=\"acceptAll\">\r\n");
      out.write("                                    모든약관에 동의합니다.\r\n");
      out.write("    \r\n");
      out.write("                                </label>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <!--//전체동의-->\r\n");
      out.write("    \r\n");
      out.write("                            <!--회원약관-->\r\n");
      out.write("                            <li class=\"itemBox\">\r\n");
      out.write("    \r\n");
      out.write("                                <input type=\"checkbox\" name=\"list\" id=\"acceptUser\">\r\n");
      out.write("    \r\n");
      out.write("                                <label for=\"acceptUser\">\r\n");
      out.write("                                    회원가입 약관(필수)\r\n");
      out.write("                                </label>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("                                <div id=\"userConditionsBox\" class=\"spec\">\r\n");
      out.write("                                    <p>\r\n");
      out.write("                                        제 1조 (목적)\r\n");
      out.write("                                        <br>\r\n");
      out.write("                                        이 약관은 전기통신 사업법 및 동 법 시행령에 의하여 \"(주)나남\"(이하 \"회사\" 라 합니다.)가 제공하는 인터넷 홈페이지 서비스 (이하 \"서비스\" 라\r\n");
      out.write("                                        합니다.)의\r\n");
      out.write("                                        이용조건 및 절차에 관한 사항, 회사와 이용자의 권리와 의무 및 책임사항을 규정함을 목적으로 합니다.\r\n");
      out.write("                                        <br>\r\n");
      out.write("                                        제 2조 (약관의 효력과 개정)\r\n");
      out.write("                                        <br>\r\n");
      out.write("                                        1. 이 약관은 전기통신사업법 제 31 조, 동 법 시행규칙 제 21조의 2에 따라 공시절차를 거친 후 홈페이지를 통하여 이를 공지하거나 전자우편\r\n");
      out.write("                                        기타의 방법으로\r\n");
      out.write("                                        이용자에게 통지함으로써 효력을 발생합니다.\r\n");
      out.write("                                        2. 회사는 본 약관을 사전 고지 없이 개정할 수 있으며, 개정된 약관은 제9조에 정한 방법으로 공지합니다. 회원은 개정된 약관에 동의하지 아니하는\r\n");
      out.write("                                        경우 본인의\r\n");
      out.write("                                        회원등록을 취소(회원탈퇴)할 수 있으며, 계속 사용의 경우는 약관 개정에 대한 동의로 간주됩니다. 개정된 약관은 공지와 동시에 그 효력이 발생됩니다.\r\n");
      out.write("                                        <br>\r\n");
      out.write("                                        제 3조 (약관이외의 준칙)\r\n");
      out.write("                                        <br>\r\n");
      out.write("                                        이 약관에 명시되어 있지 않은 사항은 전기통신 기본법, 전기통신 사업법, 기타 관련법령의 규정에 따릅니다.\r\n");
      out.write("                                        <br>\r\n");
      out.write("                                        제 4조 (용어의 정의)\r\n");
      out.write("                                        <br>\r\n");
      out.write("                                        이 약관에서 사용하는 용어의 정의는 다음과 같습니다.\r\n");
      out.write("                                        <br>\r\n");
      out.write("                                        1. 회원 : 서비스에 개인정보를 제공하여 회원등록을 한 자로서, 서비스의 정보를 지속적으로 제공받으며, 이용할 수 있는 자를 말합니다.\r\n");
      out.write("                                        2. 이용자 : 본 약관에 따라 회사가 제공하는 서비스를 받는 회원 및 비회원을 말합니다.\r\n");
      out.write("                                        3. 아이디 (ID) : 회원 식별과 회원의 서비스 이용을 위하여 회원이 선정하고 회사가 승인하는 문자와 숫자의 조합을 말합니다.\r\n");
      out.write("                                        4. 비밀번호 : 회원이 통신상의 자신의 비밀을 보호하기 위해 선정한 문자와 숫자의 조합을 말합니다.\r\n");
      out.write("                                        5. 전자우편 (E-mail) : 인터넷을 통한 우편입니다.\r\n");
      out.write("                                        6. 해지 : 회사 또는 회원이 서비스 이용 이후 그 이용계약을 종료 시키는 의사표시를 말합니다.\r\n");
      out.write("                                        7. 홈페이지 : 회사가 이용자에게 서비스를 제공하기 위하여 컴퓨터 등 정보통신설비를 이용하여 이용자가 열람 및 이용할 수 있도록 설정한 가상의 서비스\r\n");
      out.write("                                        공간을\r\n");
      out.write("                                        말합니다\r\n");
      out.write("                                        <br>\r\n");
      out.write("                                        제 5조 (서비스의 제공 및 변경)\r\n");
      out.write("                                        <br>\r\n");
      out.write("                                        1. 회사가 제공하는 서비스는 다음과 같습니다.\r\n");
      out.write("                                        <br>\r\n");
      out.write("                                        1) 회사에 대한 홍보 내용\r\n");
      out.write("                                        2) 회사가 판매하는 제품 안내\r\n");
      out.write("                                        3) 기타 회사가 제공하는 각종 정보\r\n");
      out.write("                                        4) 고객 상담 서비스\r\n");
      out.write("                                        5) 회원 이용 서비스\r\n");
      out.write("                                        <br>\r\n");
      out.write("                                        2. 회사는 필요한 경우 서비스의 내용을 추가 또는 변경하여 제공할 수 있습니다.\r\n");
      out.write("                                        <br>\r\n");
      out.write("                                        제 6조 (서비스의 중단)\r\n");
      out.write("                                        <br>\r\n");
      out.write("                                        1. 회사는 컴퓨터 등 정보통신설비의 보수점검/교체 및 고장, 통신의 두절 등의 사유가 발생한 경우에는 서비스의 제공을 일시적으로 중단할 수 있습니다.\r\n");
      out.write("                                        2. 제 1항에 의한 서비스 중단의 경우에는 제 9조에 정한 방법으로 이용자에게 통지합니다.\r\n");
      out.write("                                        3. 회사는 제1항의 사유로 서비스의 제공이 일시적으로 중단됨으로 인하여 이용자 또는 제3자가 입은 손해에 대하여 배상하지 아니합니다. 단, 회사에\r\n");
      out.write("                                        고의 또는\r\n");
      out.write("                                        중과실이 있는 경우에는 그러하지 아니합니다.\r\n");
      out.write("                                        <br>\r\n");
      out.write("                                        제 7조 (회원가입)\r\n");
      out.write("                                        <br>\r\n");
      out.write("                                        1. 이용자는 회사가 정한 가입양식에 따라 회원정보를 기입한 후 이 약관에 동의한다는 의사표시를 함으로서 회원가입을 신청합니다.\r\n");
      out.write("                                        2. 이용자는 반드시 실명으로 회원가입을 하여야 하며, 1개의 이름에 대해 1건의 회원가입 신청을 할 수 있습니다.\r\n");
      out.write("                                        3. 회사는 제 1항과 같이 회원으로 가입할 것을 신청한 이용자 중 다음 각 호에 해당하지 않는 한 회원으로 등록합니다.\r\n");
      out.write("                                        1) 이름이 실명이 아닌 경우\r\n");
      out.write("                                        2) 등록 내용에 허위, 기재누락, 오기가 있는 경우\r\n");
      out.write("                                        3) 타인의 명의를 사용하여 신청한 경우\r\n");
      out.write("                                        4) 가입신청자가 이 약관 제 8조 3항에 의하여 이전에 회원자격을 상실한 적이 있는 경우(단, 제 8조 3항에 의한 회원자격 상실 후 3년이 경과한\r\n");
      out.write("                                        자로서 회사의\r\n");
      out.write("                                        회원 재가입 승낙을 얻은 경우는 예외로 합니다.)\r\n");
      out.write("                                        5) 만 14세 미만의 아동\r\n");
      out.write("                                        6) 기타 회원으로 회사 소정의 이용신청요건을 충족하지 못하는 경우\r\n");
      out.write("                                        4. 회원가입계약의 성립시기는 회사의 승낙이 이용자에게 도달한 시점으로 합니다.\r\n");
      out.write("                                        5. 회원은 제 10조 1항에 의한 등록사항에 변경이 있는 경우 회원정보변경 항목을 통해 직접 변경사항을 수정, 등록하여야 합니다.\r\n");
      out.write("                                        <br>\r\n");
      out.write("                                        제 8조 (회원탈퇴 및 자격 상실 등)\r\n");
      out.write("                                        1. 회원은 언제든지 회원의 탈퇴를 홈페이지에 요청할 수 있으며, 홈페이지는 즉시 이에 응합니다.\r\n");
      out.write("                                        2. 회원이 다음 각 호의 사유에 해당하는 경우, 회사는 회원자격을 제한 및 정지시킬 수 있습니다.\r\n");
      out.write("                                        1) 가입 신청 시에 허위 내용을 등록한 경우\r\n");
      out.write("                                        2) 타인의 서비스 이용을 방해하거나 그 정보를 도용하는 등 서비스 운영질서를 위협하는 경우\r\n");
      out.write("                                        3) 서비스를 이용하여 법령과 이 약관이 금지하거나, 공서양속에 반하는 행위를 하는 경우\r\n");
      out.write("                                        4) 제 13조 에 명기된 회원의 의무사항을 준수하지 못할 경우\r\n");
      out.write("                                        3. 회사가 회원자격을 제한/정지시킨 후, 동일한 행위가 2회 이상 반복되거나 30일 이내에 그 사유가 시정되지 아니하는 경우 회사는 회원자격을 상실\r\n");
      out.write("                                        시킬 수\r\n");
      out.write("                                        있습니다.\r\n");
      out.write("                                        4. 회사가 회원자격을 상실 시키는 경우 회원에게 이를 통지하고 탈퇴를 처리합니다. 이 경우 회원에게 이를 통지하고, 탈퇴 전에 소명할 기회를\r\n");
      out.write("                                        부여합니다.\r\n");
      out.write("                                        <br>\r\n");
      out.write("                                        제 9조 (이용자에 대한 통지)\r\n");
      out.write("                                        1. 회사가 이용자에 대한 통지를 하는 경우, 이용자가 서비스에 제출한 전자우편 주소로 할 수 있습니다.\r\n");
      out.write("                                        2. 회사가 불특정 다수 이용자에 대한 통지의 경우 1주일 이상 서비스 게시판에 게시함으로써 개별 통지에 갈음할 수 있습니다.\r\n");
      out.write("                                        <br>\r\n");
      out.write("                                        제 10조 (개인 정보 보호)\r\n");
      out.write("                                        <br>\r\n");
      out.write("                                        1. 회사는 이용자 정보 수집 시 회사측이 필요한 최소한의 정보를 수집합니다. 다음 사항을 필수사항으로 하며 그 외 사항은 선택사항으로 합니다.\r\n");
      out.write("                                        1) 성명\r\n");
      out.write("                                        2) 희망 ID\r\n");
      out.write("                                        3) 비밀번호\r\n");
      out.write("                                        4) E-mail\r\n");
      out.write("                                        5) 주소\r\n");
      out.write("                                        6) 전화번호\r\n");
      out.write("                                        7) favor 구독 여부\r\n");
      out.write("                                        <br>\r\n");
      out.write("                                        2. 회사가 이용자의 개인식별이 가능한 개인정보를 수집하는 때에는 반드시 당해 이용자의 동의를 받습니다.\r\n");
      out.write("                                        <br>\r\n");
      out.write("                                        3. 제공된 개인정보는 당해 이용자의 동의 없이 제 3자에게 제공할 수 없으며, 이에 대한 모든 책임은 회사가 집니다. 다만 다음의 경우에는 예외로\r\n");
      out.write("                                        합니다.\r\n");
      out.write("                                        1) 배송업무상 배송업체에게 배송에 필요한 최소한의 이용자의 정보(성명, 주소, 전화번호)를 알려주는 경우\r\n");
      out.write("                                        2) 통계작성, 학술연구 또는 시장조사를 위하여 필요한 경우로서 특정 개인을 식별할 수 없는 형태로 제공하는 경우\r\n");
      out.write("                                        3) 관계법령에 의하여 국가기관으로부터 요구 받은 경우\r\n");
      out.write("                                        4) 범죄에 대한 수사상의 목적이 있거나, 정보통신 윤리위원회의 요청이 있는 경우\r\n");
      out.write("                                        5) 기타 관계법령에서 정한 절차에 따른 요청이 있는 경우\r\n");
      out.write("                                        <br>\r\n");
      out.write("                                        4. 이용자는 언제든지 회사가 가지고 있는 자신의 개인정보에 대해 열람 및 오류정정을 할 수 있습니다.\r\n");
      out.write("                                        <br>\r\n");
      out.write("                                        5. 회사로부터 개인정보를 제공받은 제 3자는 개인정보를 제공받은 목적을 달성한 때에는 당해 개인정보를 지체 없이 파기합니다.\r\n");
      out.write("                                        <br>\r\n");
      out.write("                                        제 11조 (회사의 의무)\r\n");
      out.write("                                        1. 회사는 이 약관에서 정한 바에 따라 계속적, 안정적으로 서비스를 제공할 수 있도록 최선의 노력을 다하여야만 합니다.\r\n");
      out.write("                                        2. 회사는 서비스에 관련된 설비를 항상 운용할 수 있는 상태로 유지/보수하고, 장애가 발생하는 경우 지체 없이 이를 수리/복구할 수 있도록 최선의\r\n");
      out.write("                                        노력을 다하여야\r\n");
      out.write("                                        합니다.\r\n");
      out.write("                                        3. 회사는 이용자가 안전하게 서비스를 이용할 수 있도록 이용자의 개인정보보호를 위한 보안시스템을 갖추어야 합니다.\r\n");
      out.write("                                        4. 회사는 이용자가 원하지 않는 영리목적의 광고성 전자우편을 발송하지 않습니다.\r\n");
      out.write("                                        <br>\r\n");
      out.write("                                        제 12조 (회원의 ID 및 비밀번호에 대한 의무)\r\n");
      out.write("                                        1. 회원에게 부여된 아이디(ID)와 비밀번호의 관리책임은 회원에게 있으며 관리 소홀, 부정사용에 의하여 발생하는 모든 결과에 대한 책임은 회원에게\r\n");
      out.write("                                        있습니다.\r\n");
      out.write("                                        2. 회원이 자신의 ID 및 비밀번호를 도난 당하거나 제 3자가 사용하고 있음을 인지한 경우에는 바로 회사에 통보하고 회사의 안내가 있는 경우에는 그에\r\n");
      out.write("                                        따라야\r\n");
      out.write("                                        합니다.\r\n");
      out.write("                                        <br>\r\n");
      out.write("                                        제 13조 (회원의 의무)\r\n");
      out.write("                                        1. 회원은 관계법령, 본 약관의 규정, 이용안내 및 주의사항 등 회사가 통지하는 사항을 준수하여야 하며, 기타 회사의 업무에 방해되는 행위를 하여서는\r\n");
      out.write("                                        안됩니다.\r\n");
      out.write("                                        2. 회원은 회사의 사전승낙 없이 서비스를 이용하여 어떠한 영리행위도 할 수 없습니다.\r\n");
      out.write("                                        3. 회원은 서비스를 이용하여 얻은 정보를 회사의 사전승낙 없이 복사, 복제, 변경, 번역, 출판/방송 기타의 방법으로 사용하거나 이를 타인에게 제공할\r\n");
      out.write("                                        수 없습니다.\r\n");
      out.write("                                        4. 회원은 자기 신상정보의 변경사항 발생시 즉각 변경하여야 합니다. 회원정보를 수정하지 않아 발생하는 모든 결과에 대한 책임은 회원에게 있습니다.\r\n");
      out.write("                                        5. 회원은 서비스 이용과 관련하여 다음 각 호의 행위를 하지 않아야 하며, 다음 행위를 함으로 발생하는 모든 결과에 대한 책임은 회원에게 있습니다.\r\n");
      out.write("                                        1) 다른 회원의 아이디(ID)를 부정하게 사용하는 행위\r\n");
      out.write("                                        2) 다른 회원의 E-mail 주소를 취득하여 스팸메일을 발송하는 행위\r\n");
      out.write("                                        3) 범죄행위를 목적으로 하거나 기타 범죄행위와 관련된 행위\r\n");
      out.write("                                        4) 선량한 풍속, 기타 사회질서를 해하는 행위\r\n");
      out.write("                                        5) 회사 및 타인의 명예를 훼손하거나 모욕하는 행위\r\n");
      out.write("                                        6) 회사 및 타인의 지적재산권 등의 권리를 침해하는 행위\r\n");
      out.write("                                        7) 해킹행위 또는 컴퓨터 바이러스의 유포행위\r\n");
      out.write("                                        8) 타인의 의사에 반하여 광고성 정보 등 일정한 내용을 지속적으로 전송하는 행위\r\n");
      out.write("                                        9) 서비스의 안정적인 운영에 지장을 주거나 줄 우려가 있는 일체의 행위\r\n");
      out.write("                                        10) 회사가 제공하는 서비스의 내용을 변경하는 행위\r\n");
      out.write("                                        11) 기타 관계법령에 위배되는 행위\r\n");
      out.write("                                        <br>\r\n");
      out.write("                                        제 14조 (게시물 삭제)\r\n");
      out.write("                                        1. 회사는 이용자가 게시하거나 등록하는 서비스내의 게시물이 제 13조의 규정에 위반되거나, 다음 각 호에 해당한다고 판단되는 경우 사전통지 없이\r\n");
      out.write("                                        게시물을 삭제할 수\r\n");
      out.write("                                        있습니다.\r\n");
      out.write("                                        1) 다른 이용자 또는 제 3자를 비방하거나 중상모략으로 명예를 손상시키는 내용\r\n");
      out.write("                                        2) 공공질서 또는 미풍양속에 위반되는 내용\r\n");
      out.write("                                        3) 범죄적 행위에 결부된다고 인정되는 내용\r\n");
      out.write("                                        4) 제 3자의 저작권 등 기타 권리를 침해하는 내용\r\n");
      out.write("                                        5) 서비스의 안정적인 운영에 지장을 주거나 줄 우려가 있는 내용\r\n");
      out.write("                                        6) 근거나 확인절차 없이 회사를 비난하거나 유언비어를 유포한 내용\r\n");
      out.write("                                        7) 기타 관계법령에 의거하여 위반된다고 판단되는 내용\r\n");
      out.write("                                        단, 독자게시판의 경우 다음과 같이 예외를 둔다.\r\n");
      out.write("                                        용량이 큰 데이터의 경우 업로드 된 게시물의 수를 제한하며 그 수를 넘을 때에는 서버의 원활한 운영을 위해 가장 오래된 게시물부터 삭제할 수 있다.\r\n");
      out.write("                                        2. 회사는 이용자가 게시하거나 등록하는 서비스내의 게시물이 제 13조의 규정에 위반되거나 동 조 제1항 각 호에 해당한다고 판단되는 정보를 링크하고\r\n");
      out.write("                                        있을 경우\r\n");
      out.write("                                        사전통지 없이 게시물을 삭제할 수 있습니다.\r\n");
      out.write("                                        <br>\r\n");
      out.write("                                        제 15조 (게시물에 대한 권리 / 의무)\r\n");
      out.write("                                        게시물에 대한 저작권을 포함한 모든 권리 및 책임은 이를 게시한 이용자에게 있습니다.\r\n");
      out.write("                                        <br>\r\n");
      out.write("                                        제 16조 (연결 \"홈페이지\"와 피연결 \"홈페이지\"간의 관계)\r\n");
      out.write("                                        1. 상위 \"홈페이지\"와 하위 \"홈페이지\"가 하이퍼 링크(예:하이퍼 링크의 대상에는 문자, 그림 및 동화상 등이 포함됨) 방식 등으로 연결된 경우,\r\n");
      out.write("                                        전자를 연결\r\n");
      out.write("                                        \"홈페이지\"라고 하고 후자를 피연결 \"홈페이지(웹사이트)\"라고 합니다.\r\n");
      out.write("                                        2. 연결 \"홈페이지\"는 피연결 \"홈페이지\"가 독자적으로 제공하는 재화?용역에 의하여 이용자와 행하는 거래에 대해서 보증책임을 지지 않습니다.\r\n");
      out.write("                                        <br>\r\n");
      out.write("                                        제 17조 (저작권의 귀속 및 이용제한)\r\n");
      out.write("                                        1. 회사가 작성한 저작물에 대한 저작권 및 기타 지적재산권은 회사에 귀속합니다.\r\n");
      out.write("                                        2. 이용자는 서비스를 이용함으로써 얻은 정보를 회사의 사전승낙 없이 복제, 송신, 출판, 배포, 방송, 기타 방법에 의하여 영리목적으로 이용하거나 제\r\n");
      out.write("                                        3자에게\r\n");
      out.write("                                        이용하게 하여서는 안됩니다.\r\n");
      out.write("                                        <br>\r\n");
      out.write("                                        제 18조 (양도금지)\r\n");
      out.write("                                        회원이 서비스의 이용권한, 기타 이용 계약상 지위를 타인에게 양도, 증여할 수 없으며, 이를 담보로 제공할 수 없습니다.\r\n");
      out.write("                                        <br>\r\n");
      out.write("                                        제 19조 (손해배상)\r\n");
      out.write("                                        회사는 무료로 제공되는 서비스와 관련하여 이용자에게 어떠한 손해가 발생하더라도 동 손해가 회사의 중대한 과실에 의한 경우를 제외하고 이에 대하여 책임을\r\n");
      out.write("                                        부여하지\r\n");
      out.write("                                        아니합니다.\r\n");
      out.write("                                        <br>\r\n");
      out.write("                                        제 20조 (면책 / 배상)\r\n");
      out.write("                                        1. 회사는 이용자가 서비스에 게재한 정보, 자료, 사실의 정확성, 신뢰성 등 그 내용에 관하여는 어떠한 책임을 부담하지 아니하고, 이용자는 자신의\r\n");
      out.write("                                        책임아래 서비스를\r\n");
      out.write("                                        이용하며, 서비스를 이용하여 게시 또는 전송한 자료 등에 관하여 손해가 발생하거나 자료의 취사선택, 기타 서비스 이용과 관련하여 어떠한 불이익이\r\n");
      out.write("                                        발생하더라도 이에\r\n");
      out.write("                                        대한 모든 책임은 이용자에게 있습니다.\r\n");
      out.write("                                        2. 회사는 제 13조의 규정에 위반하여 이용자간 또는 이용자와 제 3자간에 서비스를 매개로 한 물품거래 등과 관련하여 어떠한 책임도 부담하지\r\n");
      out.write("                                        아니하고, 이용자가\r\n");
      out.write("                                        서비스의 이용과 관련하여 기대하는 이익에 관하여 책임을 부담하지 않습니다.\r\n");
      out.write("                                        3. 이용자가 제 13조, 기타 이 약관의 규정을 위반함으로 인하여 회사가 이용자 또는 제 3자에 대하여 책임을 부담하게 되고, 이로써 회사에게 손해가\r\n");
      out.write("                                        발생하게 되는\r\n");
      out.write("                                        경우, 이 약관을 위반한 이용자는 회사에게 발생하는 모든 손해를 배상하여야 하며, 동 손해로부터 회사를 면책시켜야 합니다.\r\n");
      out.write("                                        <br>\r\n");
      out.write("                                        제 21조 (분쟁의 해결)\r\n");
      out.write("                                        1. 회사와 이용자는 서비스와 관련하여 발생한 분쟁을 원만하게 해결하기 위하여 필요한 모든 노력을 하여야 합니다.\r\n");
      out.write("                                        2. 제 1항의 규정에도 불구하고, 동 분쟁으로 인하여 소송이 제기될 경우 동 소송은 서울지방법원을 관할로 합니다.\r\n");
      out.write("                                        3. 동 소송에는 대한민국 법을 적용합니다.\r\n");
      out.write("                                        <br>\r\n");
      out.write("                                        제 22조 (기타)\r\n");
      out.write("                                        이 약관에 명시되지 아니한 사항의 처리를 위하여 이용자는 담당자에게 문의해주시면 됩니다.\r\n");
      out.write("                                        <br>\r\n");
      out.write("                                        부칙\r\n");
      out.write("                                        이 약관은 2017년 06월 10일부터 시행합니다.\r\n");
      out.write("                                    </p>\r\n");
      out.write("    \r\n");
      out.write("                                </div>\r\n");
      out.write("    \r\n");
      out.write("                            </li>\r\n");
      out.write("                            <!--//회원약관-->\r\n");
      out.write("    \r\n");
      out.write("                            <!--개인정보 수집 이용 동의-->\r\n");
      out.write("                            <li class=\"itemBox\">\r\n");
      out.write("                                <input type=\"checkbox\" name=\"list\" id=\"acceptPrivate\">\r\n");
      out.write("                                <label for=\"acceptPrivate\">\r\n");
      out.write("                                    개인정보 수집 이용 동의 (필수)\r\n");
      out.write("                                </label>\r\n");
      out.write("    \r\n");
      out.write("                                <div id=\"emailConditionsBox\" class=\"spec\">\r\n");
      out.write("                                    <p>\r\n");
      out.write("                                        <br>\r\n");
      out.write("                                        ■ 수집하는 개인정보 항목\r\n");
      out.write("                                        <br>\r\n");
      out.write("                                        우리 회사는 회원가입, 상담, 서비스 신청 등등을 위해 아래와 같은 개인정보를 수집하고 있습니다.\r\n");
      out.write("                                        <br>\r\n");
      out.write("                                        ο 수집항목 : 이름 , 로그인ID , 비밀번호 , 전화번호 , 주소, 휴대전화번호 , 이메일 , 서비스 이용기록 , 접속 로그 , 쿠키 , 접속 IP\r\n");
      out.write("                                        정보\r\n");
      out.write("                                        ο 개인정보 수집방법 : 홈페이지(회원가입)\r\n");
      out.write("    \r\n");
      out.write("                                        <br>\r\n");
      out.write("                                        ■ 개인정보의 수집 및 이용목적\r\n");
      out.write("                                        <br>\r\n");
      out.write("                                        우리 회사는 수집한 개인정보를 다음의 목적을 위해 활용합니다.\r\n");
      out.write("                                        <br>\r\n");
      out.write("                                        ο 회원 관리\r\n");
      out.write("                                        회원제 서비스 이용에 따른 본인확인 , 개인 식별 , 불량회원의 부정 이용 방지와 비인가 사용 방지 , 가입 의사 확인 , 불만처리 등 민원처리 ,\r\n");
      out.write("                                        고지사항 전달\r\n");
      out.write("                                        <br>\r\n");
      out.write("                                        <br>\r\n");
      out.write("                                        ■ 개인정보의 보유 및 이용기간\r\n");
      out.write("                                        <br>\r\n");
      out.write("                                        원칙적으로, 개인정보 수집 및 이용목적이 달성된 후에는 해당 정보를 지체 없이 파기합니다. 단, 관계법령의 규정에 의하여 보존할 필요가 있는 경우\r\n");
      out.write("                                        회사는 아래와 같이\r\n");
      out.write("                                        관계법령에서 정한 일정한 기간 동안 회원정보를 보관합니다.\r\n");
      out.write("                                        <br>\r\n");
      out.write("                                        - 보존 항목 : 이름, 로그인ID, 결제기록, 주문정보, 배송정보\r\n");
      out.write("                                        - 보존 근거 : 서비스 이용의 혼선 방지\r\n");
      out.write("                                        - 보존 기간 : 5년 상법, 전자상거래 등에서의 소비자보호에 관한 법률 등 관계법령의 규정에 의하여 보존할 필요가 있는 경우 회사는 관계법령에서 정한\r\n");
      out.write("                                        일정한 기간\r\n");
      out.write("                                        동안 회원정보를 보관합니다. 이 경우 회사는 보관하는 정보를 그 보관의 목적으로만 이용하며 보존기간은 아래와 같습니다.\r\n");
      out.write("                                        <br>\r\n");
      out.write("                                        - 계약 또는 청약철회 등에 관한 기록 : 5년 (전자상거래등에서의 소비자보호에 관한 법률)\r\n");
      out.write("                                        - 대금결제 및 재화 등의 공급에 관한 기록 : 5년 (전자상거래등에서의 소비자보호에 관한 법률)\r\n");
      out.write("                                        - 소비자의 불만 또는 분쟁처리에 관한 기록 : 3년 (전자상거래등에서의 소비자보호에 관한 법률)\r\n");
      out.write("                                        - 신용정보의 수집/처리 및 이용 등에 관한 기록 : 3년 (신용정보의 이용 및 보호에 관한 법률)\r\n");
      out.write("                                    </p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <!--//개인정보 수집 이용 동의-->\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("                        </ul>\r\n");
      out.write("                        <!--//약관동의서-->\r\n");
      out.write("    \r\n");
      out.write("                        <!---버튼-->\r\n");
      out.write("                        <ul id=\"btnWrap\">\r\n");
      out.write("                            <!--취소버튼-->\r\n");
      out.write("                            <li id=\"leftBtn\">\r\n");
      out.write("                                <a class=\"resetBtn\" href=\"#\" id=\"reset\" title=\"취소\" role=\"button\"\r\n");
      out.write("                                    onclick=\"location.href=resetPage();\">취소</a>\r\n");
      out.write("    \r\n");
      out.write("                            </li>\r\n");
      out.write("                            <!--취소버튼-->\r\n");
      out.write("    \r\n");
      out.write("                            <!--확인버튼-->\r\n");
      out.write("                            <li id=\"rightBtn\">\r\n");
      out.write("                                <a class=\"submitBtn\" id=\"submit\" title=\"가입\" role=\"button\"\r\n");
      out.write("                                   href=\"#\" onclick=\"location.href=goNextPage();\">확인\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            \r\n");
      out.write("                        </ul>\r\n");
      out.write("                        \r\n");
      out.write("                    </form>\r\n");
      out.write("    \r\n");
      out.write("                </div>\r\n");
      out.write("                <!--//폼랩-->\r\n");
      out.write("    \r\n");
      out.write("            </div>\r\n");
      out.write("            <!--//약관동의/회원가입 선택창-->\r\n");
      out.write("   \r\n");
      out.write("        </div>\r\n");
      out.write("          <!--//inner 약관동의-->\r\n");
      out.write("    </div>\r\n");
      out.write("    <!--//약관동의-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nanam}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/footer.css\"/>\r\n");
      out.write("   <!--푸터-->\r\n");
      out.write("    <div id=\"footerWrap\">\r\n");
      out.write("\r\n");
      out.write("        <div id=\"footerBox\">\r\n");
      out.write("            <img alt=\"화면 제일 하단 로고\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nanam }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/arr/logo2.gif\">\r\n");
      out.write("            <div id=\"copy\">\r\n");
      out.write("                <ul id=\"footerList\">\r\n");
      out.write("\r\n");
      out.write("                    <li><a title=\"오시는길\" href=\"#\">오시는 길</a></li>\r\n");
      out.write("                    <li><a title=\"사이트맵\" href=\"#\">사이트맵</a></li>\r\n");
      out.write("                    <li><a title=\"이용약관\" href=\"#\">이용약관</a></li>\r\n");
      out.write("                    <li><a title=\"개인정보취급방침\" href=\"#\">개인정보취급방침</a></li>\r\n");
      out.write("                    <li><a title=\"이메일무단수집거부\" href=\"#\">이메일무단수집거부</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <address>\r\n");
      out.write("                    (주)나남 전화 : 031-955-4600 팩스 : 031-955-4555 이메일 : webmaster@nanam.net\r\n");
      out.write("                    주소 : 경기도 파주시 회동길 193 (문발동, 파주출판단지)\r\n");
      out.write("                    통신판매업신고 : 마포 제2786호 사업자등록번호 : 214-81-63262 사업자정보확인 >\r\n");
      out.write("\r\n");
      out.write("                </address>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!--//푸터-->\r\n");
      out.write("    \r\n");
      out.write("    </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /member/../main/header.jsp(8,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("nanam");
      // /member/../main/header.jsp(8,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f1_reused = false;
    try {
      _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f1.setParent(null);
      // /member/../main/header.jsp(48,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setVar("leaveOut");
      // /member/../main/header.jsp(48,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${leaveOut}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
      if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      _jspx_th_c_005fset_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t\t");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /member/../main/header.jsp(71,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty sessionScope.login}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t\t<li><a title=\"로그인\" href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nanam}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member/loginFront\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t로그인</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t\t<li><a title=\"회원가입페이지로 이동\" href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nanam}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member/agreeFront\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t회원가입</a></li>\r\n");
          out.write("\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t<li><a title=\"로그아웃\" href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nanam}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member/logoutFront\">로그아웃\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t</a></li>\r\n");
          out.write("\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t");
          if (_jspx_meth_c_005fif_005f0(_jspx_th_c_005fotherwise_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fotherwise_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fotherwise_005f0);
      // /member/../main/header.jsp(88,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.login.id ne 'scott' and login.pwd ne 'tiger'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t<li><a title=\"회원 탈퇴 페이지로 이동\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\thref=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nanam}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member/leaveOutFront\"> 회원탈퇴</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t<li><a href=\"javascript:openWindowPop();\">포인트 충전</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t<li><a title=\"정보수정 페이지로 이동\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\thref=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nanam}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member/myPageInfo\"> 정보수정 </a></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t\t\t<li><a title=\"포인트 결과로 이동\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\thref=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nanam}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member/myPageResult\"> 보유 포인트 결과</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t<li><a title=\"장바구니로 이동\"\r\n");
          out.write("\t\t\t\t\t\t\t\t\thref=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nanam}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/pay/cartBookSelect?hid=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${login.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"> 장바구니</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f1 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f1_reused = false;
    try {
      _jspx_th_c_005fchoose_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f1.setParent(null);
      int _jspx_eval_c_005fchoose_005f1 = _jspx_th_c_005fchoose_005f1.doStartTag();
      if (_jspx_eval_c_005fchoose_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t");
          if (_jspx_meth_c_005fwhen_005f1(_jspx_th_c_005fchoose_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f1);
      _jspx_th_c_005fchoose_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f1 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f1_reused = false;
    try {
      _jspx_th_c_005fwhen_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
      // /member/../main/header.jsp(173,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.login.id eq'scott' and login.pwd eq 'tiger'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f1 = _jspx_th_c_005fwhen_005f1.doStartTag();
      if (_jspx_eval_c_005fwhen_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<li><a title=\"글쓰기\" href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nanam}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/book/inputBookFront\">책 글쓰기 \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t\t\t\t</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f1);
      _jspx_th_c_005fwhen_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f2 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f2_reused = false;
    try {
      _jspx_th_c_005fchoose_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f2.setParent(null);
      int _jspx_eval_c_005fchoose_005f2 = _jspx_th_c_005fchoose_005f2.doStartTag();
      if (_jspx_eval_c_005fchoose_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t");
          if (_jspx_meth_c_005fwhen_005f2(_jspx_th_c_005fchoose_005f2, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f2);
      _jspx_th_c_005fchoose_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f2 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f2_reused = false;
    try {
      _jspx_th_c_005fwhen_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f2);
      // /member/../main/header.jsp(201,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.login.id eq'scott' and login.pwd eq 'tiger'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f2 = _jspx_th_c_005fwhen_005f2.doStartTag();
      if (_jspx_eval_c_005fwhen_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<li><a title=\"글쓰기\" href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nanam}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/board/inputNoticeFront\">글쓰기 \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t\t\t\t</a></li>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f2);
      _jspx_th_c_005fwhen_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f2_reused);
    }
    return false;
  }
}
