CREATE TABLE DEPT_TEMP
    AS SELECT * FROM DEPT;

CREATE TABLE EMP_TEMP10
    AS SELECT * FROM EMP;
    
INSERT 
  INTO DEPT_TEMP (DEPTNO, DNAME, LOC)
VALUES (50,'DATABASE','SEOUL');

SELECT * FROM DEPT_TEMP;

INSERT 
  INTO DEPT_TEMP (DEPTNO, DNAME, LOC)
VALUES (60,'NETWORK','BUSAN');

SELECT * FROM DEPT_TEMP;

INSERT 
  INTO DEPT_TEMP (DEPTNO, DNAME, LOC)
VALUES (70,'WEB',NULL);

SELECT * FROM DEPT_TEMP;

INSERT 
  INTO DEPT_TEMP (DEPTNO, DNAME, LOC)
VALUES (80,'MOBILE','');

SELECT * FROM DEPT_TEMP;

INSERT 
  INTO DEPT_TEMP (DEPTNO,  LOC)
VALUES (90,'INCHEON');

SELECT * FROM DEPT_TEMP;

-- 1<>1 결과값은 항상 false 그래서 모든행을 복사하지 않음
CREATE TABLE EMP_TEMP
    AS SELECT * FROM EMP WHERE 1<>1;
    
INSERT 
  INTO EMP_TEMP (EMPNO , ENAME , JOB , MGR , HIREDATE , SAL , COMM , DEPTNO)
         VALUES (9999 , '홍길동', 'PRESIDENT', NULL , '2001/01/01' , 5000 , 1000 , 10);

SELECT * FROM EMP_TEMP;

    
INSERT 
  INTO EMP_TEMP (EMPNO , ENAME , JOB , MGR , HIREDATE , SAL , COMM , DEPTNO)
         VALUES (1111 , '성춘향', 'MANAGER', 9999 , '2001-01-05' , 4000 , NULL , 20);

SELECT * FROM EMP_TEMP;

-- 운영체제에 따라 표기방식이 다르기 때문에 날짜 데이터를 INSERT 문을 입력할때는 TO_DATE 함수 권장

INSERT 
  INTO EMP_TEMP (EMPNO , ENAME , JOB , MGR , HIREDATE , SAL , COMM , DEPTNO)
         VALUES (2111 , '이순신', 'MANAGER', 9999 , TO_DATE('07/01/2001','DD/MM/YYYY') , 4000 , NULL , 20);

SELECT * FROM EMP_TEMP;


INSERT 
  INTO EMP_TEMP (EMPNO , ENAME , JOB , MGR , HIREDATE , SAL , COMM , DEPTNO)
         VALUES (3111 , '심청이', 'MANAGER', 9999 , SYSDATE , 4000 , NULL , 30);

SELECT * FROM EMP_TEMP;

--서브 쿼리로 여러데이터 추가하기
-- VALUES 절은 사용하지 않음
-- 열의 갯수가 일치
-- 열의 자료형이 일칭
INSERT 
  INTO EMP_TEMP (EMPNO , ENAME , JOB , MGR , HIREDATE , SAL , COMM , DEPTNO)
         SELECT E.EMPNO, E.ENAME , E.JOB , E.MGR , E.HIREDATE , E.SAL , E.COMM, E.DEPTNO 
           FROM EMP E, SALGRADE S
		  WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL 
		    AND S.GRADE =1
		    ;
	

SELECT * FROM EMP_TEMP;
		   
CREATE TABLE DEPT_TEMP2
          AS SELECT * FROM DEPT 
          ;
          
SELECT * FROM DEPT_TEMP2;

UPDATE DEPT_TEMP2 SET LOC = 'SEOUL';

SELECT * FROM DEPT_TEMP2;

ROLLBACK;

DROP TABLE DEPT_TEMP2;

COMMIT;

UPDATE DEPT_TEMP2
   SET DNAME = 'DATABASE',
       LOC   = 'SEOUL'
 WHERE DEPTNO = 40
 ;
 
UPDATE EMP_TEMP 
   SET COMM = 50
 WHERE SAL <=2500
 
 UPDATE DEPT_TEMP2
    SET (DNAME, LOC) = (SELECT DNAME, LOC FROM DEPT WHERE DEPTNO = 40)
  WHERE DEPTNO = 40
    ;
    
   SELECT * FROM DEPT_TEMP2
   
 UPDATE DEPT_TEMP2
    SET DNAME='OPERATIONS'
  WHERE DEPTNO = (SELECT DEPTNO FROM DEPT_TEMP2 WHERE LOC = 'SEOUL');
  
 
 UPDATE DEPT_TEMP2
    SET DNAME = 'DATABASE'
      , LOC = 'SEOUL'
  WHERE DEPTNO = 40
  ;
  
  CREATE TABLE EMP_TEMP2
            AS SELECT * FROM EMP;
            
  DELETE 
    FROM EMP_TEMP2 
   WHERE JOB = 'MANAGER'
   ;
   
   SELECT * FROM EMP_TEMP2 ;
   
  DELETE 
    FROM EMP_TEMP2
   WHERE EMPNO IN (SELECT E.EMPNO
                   FROM EMP_TEMP2 E
                   INNER JOIN SALGRADE S
                      ON E.SAL BETWEEN S.LOSAL AND S.HISAL 
                   WHERE S.GRADE = 3
                     AND DEPTNO = 30 
                   );
                   
   SELECT * FROM EMP_TEMP2;
   
   CREATE TABLE CHAP10HW_EMP AS SELECT * FROM EMP
   CREATE TABLE CHAP10HW_DEPT AS SELECT * FROM DEPT;
   CREATE TABLE CHAP10HW_SALGRADE AS SELECT * FROM SALGRADE ;
   
  
	INSERT INTO CHAP10HW_DEPT (DEPTNO, DNAME, LOC) VALUES (50, 'ORACLE', 'BUSAN'); 
	
	INSERT INTO CHAP10HW_DEPT (DEPTNO, DNAME, LOC) VALUES (60, 'SQL', 'ILSAN');
	
	INSERT INTO CHAP10HW_DEPT (DEPTNO, DNAME, LOC) VALUES (70, 'SELECT', 'INCHEON');
	
	INSERT INTO CHAP10HW_DEPT (DEPTNO, DNAME, LOC) VALUES (80, 'DML', 'BUNDANG'); 
	
	INSERT INTO CHAP10HW_EMP
	VALUES(7201, 'TEST_USER1', 'MANAGER', 7788, TO_DATE('2016-01-02', 'YYYY-MM-DD'), 4500, NULL, 50);
	 
	INSERT INTO CHAP10HW_EMP
	VALUES(7202, 'TEST_USER2', 'CLERK', 7201, TO_DATE('2016-02-21', 'YYYY-MM-DD'), 1800, NULL, 50);
	 
	INSERT INTO CHAP10HW_EMP
	VALUES(7203, 'TEST_USER3', 'ANALYST', 7201, TO_DATE('2016-04-11', 'YYYY-MM-DD'), 3400, NULL, 60);
	 
	INSERT INTO CHAP10HW_EMP
	VALUES(7204, 'TEST_USER4', 'SALESMAN', 7201, TO_DATE('2016-05-31', 'YYYY-MM-DD'), 2700, 300, 60);
	 
	INSERT INTO CHAP10HW_EMP
	VALUES(7205, 'TEST_USER5', 'CLERK', 7201, TO_DATE('2016-07-20', 'YYYY-MM-DD'), 2600, NULL, 70);
	 
	INSERT INTO CHAP10HW_EMP
	VALUES(7206, 'TEST_USER6', 'CLERK', 7201, TO_DATE('2016-09-08', 'YYYY-MM-DD'), 2600, NULL, 70);
	 
	INSERT INTO CHAP10HW_EMP
	VALUES(7207, 'TEST_USER7', 'LECTURER', 7201, TO_DATE('2016-10-28', 'YYYY-MM-DD'), 2300, NULL, 80);
	 
	INSERT INTO CHAP10HW_EMP
	VALUES(7208, 'TEST_USER8', 'STUDENT', 7201, TO_DATE('2018-03-09', 'YYYY-MM-DD'), 1200, NULL, 80);
	
	UPDATE CHAP10HW_EMP
	   SET DEPTNO = 70
	 WHERE SAL > (SELECT AVG(SAL)
	                FROM CHAP10HW_EMP
	               WHERE DEPTNO = 50);
	
	UPDATE CHAP10HW_EMP
	   SET SAL = SAL*1.1,
	       DEPTNO = 80
	 WHERE HIREDATE > (SELECT MIN(HIREDATE)
	                     FROM CHAP10HW_EMP
	                    WHERE DEPTNO = 60);
	
	DELETE FROM CHAP10HW_EMP
	 WHERE EMPNO IN (SELECT E.EMPNO
	                   FROM CHAP10HW_EMP E, CHAP10HW_SALGRADE S
	                  WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
	                    AND S.GRADE = 5);
