
/*NOT NULL 제약조건*/
CREATE TABLE TABLE_NOTNIULL(
		LOGIN_ID 	VARCHAR2(20) 	NOT NULL,
	    LOGIN_PWD 	VARCHAR2(20) 	NOT NULL,
		TEL			VARCHAR2(20)
);

ALTER TABLE TABLE_NOTNIULL RENAME TO TABLE_NOTNULL;

-- NOT NULL 제약 조건으로 인한 오류
INSERT INTO TABLE_NOTNULL ( LOGIN_ID , LOGIN_PWD , TEL )
       VALUES ( 'TEST_ID_01' , NULL , '010-1234-5678'  )
  ;
  
INSERT INTO TABLE_NOTNULL ( LOGIN_ID , LOGIN_PWD  )
       VALUES ( 'TEST_ID_01' , '1234' )
       ;

-- 제약 조건 조회
SELECT OWNER , CONSTRAINT_NAME , CONSTRAINT_TYPE ,TABLE_NAME
  FROM USER_CONSTRAINTS;
 

CREATE TABLE TABLE_NOTNIULL(
		LOGIN_ID 	VARCHAR2(20) CONSTRAINT TBLNM2_LOGID_NN NOT NULL,
	    LOGIN_PWD 	VARCHAR2(20) CONSTRAINT TBLNM2_LOGPW_NN NOT NULL,
		TEL			VARCHAR2(20)
); 

ALTER TABLE TABLE_NOTNIULL RENAME TO TABLE_NOTNULL2;

SELECT OWNER , CONSTRAINT_NAME , CONSTRAINT_TYPE ,TABLE_NAME
  FROM USER_CONSTRAINTS;

 UPDATE TABLE_NOTNULL
    SET TEL='010-1234-5678'
  WHERE LOGIN_ID = 'TEST_ID_01'
  
  ;
 
  SELECT * FROM TABLE_NOTNULL 
  ;
  
 ALTER TABLE TABLE_NOTNULL MODIFY (TEL NOT NULL);
  
 SELECT OWNER , CONSTRAINT_NAME , CONSTRAINT_TYPE ,TABLE_NAME
 FROM USER_CONSTRAINTS;
 
 ALTER TABLE TABLE_NOTNULL2 
 MODIFY (TEL CONSTRAINT TABLE_TEL_NM NOT NULL); 
 
 SELECT OWNER , CONSTRAINT_NAME , CONSTRAINT_TYPE ,TABLE_NAME
 FROM USER_CONSTRAINTS;
 
 ALTER TABLE TABLE_NOTNULL2 
 RENAME CONSTRAINT TABLE_TEL_NM TO TABLENN2_TEL_NN;
 
 ALTER TABLE TABLE_NOTNULL2 
 DROP CONSTRAINT TABLENN2_TEL_NN
 ;

 /*유니크 제약조건*/
 
 CREATE TABLE TABLE_UNIQUE (
 	
 	LOGIN_ID 	VARCHAR2(20) UNIQUE,
 	LOGIN_PWD   VARCHAR2(20) NOT NULL,
    TEL         VARCHAR2(20)
 );
 
 SELECT OWNER , CONSTRAINT_NAME , CONSTRAINT_TYPE ,TABLE_NAME
 FROM USER_CONSTRAINTS
 WHERE TABLE_NAME ='TABLE_UNIQUE'
 ;

 INSERT INTO TABLE_UNIQUE (LOGIN_ID , LOGIN_PWD , TEL)
       VALUES ('TEST_ID_02' , 'PWD01' , '010-1234-5678')
       ;
       
 -- UNIQUE는 널값은 허용 중복값은 허용X      
 INSERT INTO TABLE_UNIQUE (LOGIN_ID , LOGIN_PWD , TEL)
       VALUES (NULL , 'PWD01' , '010-1234-5678')
       ;
 SELECT *
   FROM TABLE_UNIQUE ;
  
  /*기본키 제약조건*/
  
 -- PRIMARY KEY = NOTNULL + UNIQUE
  
  CREATE TABLE TABLE_PK(
 
  	LOGIN_ID  VARCHAR2(20) PRIMARY KEY,
  	LOGIN_PWD VARCHAR2(20) NOT NULL,
  	TEL       VARCHAR2(20) 

  );
 
 SELECT OWNER , CONSTRAINT_NAME , CONSTRAINT_TYPE , TABLE_NAME
   FROM USER_CONSTRAINTS 
  WHERE TABLE_NAME LIKE 'TABLE_PK%'
 ;

  SELECT INDEX_NAME , TABLE_OWNER , TABLE_NAME
    FROM USER_INDEXES
   WHERE TABLE_NAME LIKE 'TABLE_PK%' 
 ;
 
  CREATE TABLE TABLE_PK2(
 
  	LOGIN_ID  VARCHAR2(20) CONSTRAINT TBL_PK2_LOGID_PK PRIMARY KEY,
  	LOGIN_PWD VARCHAR2(20) CONSTRAINT TBL_PK2_LOGPW_NN NOT NULL,
  	TEL       VARCHAR2(20) 

  );

 /* 참조사항 아웃오브라인 테이블 라벨 제약조건
  CREATE TABLE TABLE_PK2(
 
  	LOGIN_ID  VARCHAR2(20) ,
  	LOGIN_PWD VARCHAR2(20) CONSTRAINT TBL_PK2_LOGPW_NN NOT NULL,
  	TEL       VARCHAR2(20),
  	CONSTRAINT TBL_PK2_LOGID_PK PRIMARY KEY(LOGIN_ID) 
  );
 */	
 
 INSERT INTO TABLE_PK ( LOGIN_ID , LOGIN_PWD , TEL )
        VALUES ( 'TEST_ID_01' , 'PWD01' , '010_1234_5678' );
  
 --PK 제약조건 위배 
 INSERT INTO TABLE_PK ( LOGIN_ID , LOGIN_PWD , TEL )
        VALUES ( 'TEST_ID_01' , 'PWD02' , '010_1234_5678' );
 
       
 /*외래키 제약조건*/ 
 SELECT OWNER, CONSTRAINT_NAME , CONSTRAINT_TYPE , TABLE_NAME, R_OWNER , R_CONSTRAINT_NAME 
   FROM USER_CONSTRAINTS
  WHERE TABLE_NAME IN ('EMP' , 'DEPT' )
  
  CREATE TABLE DEPT_FK(
  
  		DEPTNO NUMBER(2) CONSTRAINT DEPTFK_DEPTNO_PK PRIMARY KEY,
  		DMANE 	VARCHAR2(14),
  		LOC 	VARCHAR2(13)
  		
  );
  
  
  CREATE TABLE EMP_FK(
  
  		EMP_NO 	 NUMBER(4) CONSTRAINT EMPFK_EMPNO_PK PRIMARY KEY,
  		ENAME  	 VARCHAR2(10),
  		JOB    	 VARCHAR2(9),
  		MGR    	 NUMBER(4),
  		HIREDATE DATE,
  		SAL    	 NUMBER(7,2),
  		COMM     NUMBER(7,2),
  		DEPTNO 	 NUMBER(2) CONSTRAINT EMPFK_DEPTNO_FK REFERENCES DEPT_FK (DEPTNO)
  
  );
  
 --EMP_FK 테이블에 데이터 삽입하기 ( DEPTNO 데이터가 아직 DEPTFK 테이블에 없을 때) 무결성제약조건 위배 부모키가 없음
 INSERT INTO EMP_FK VALUES (9999, 'TEST_NMAME' , 'TEST_JOB', NULL , TO_DATE('2001/01/01' , 'YYYY/MM/DD'), 3000,NULL, 10);
  
 --DEPT_FK에 데이터 삽입하기
 INSERT INTO DEPT_FK VALUES (10, 'TEST_DNAME', 'TEST_LOC');
  
 --이제 가능
 INSERT INTO EMP_FK VALUES (9999, 'TEST_NMAME' , 'TEST_JOB', NULL , TO_DATE('2001/01/01' , 'YYYY/MM/DD'), 3000,NULL, 10);
 
 --외래키도 참조행 데이터 삭제하기 --무결성 제약조건 위배 자식키가 발견됨
 DELETE FROM DEPT_FK WHERE DEPTNO = 10;
 
 -- 그래서 테이블을 생성할 때 카스케이드 옵션을 설정함
 -- CONSTRINT [제약조건 이름] REFERENCES 참조테이블 (참조할 열) ON DELETE CASCADE
 -- CONSTRINT [제약조건 이름] REFERENCES 참조테이블 (참조할 열) ON DELETE SET NULL;

	/*CHECK 제약 조건*/
 --데이터 형태와 범위를 정하는 check 
 -- 열에 저장할 수 있는 값의 범위 또는 패턴천을 정의할 때 사용 

  CREATE TABLE TABLE_CHECK (
       LOGIN_ID  VARCHAR2(20) CONSTRAINT TBLCK_LOGINID_PK PRIMARY KEY,
       LOGIN_PWD VARCHAR2(20) CONSTRAINT TBLCK_LOGINPWD_CK CHECK (LENGTH (LOGIN_PWD) >3),
       TEL       VARCHAR2(20)
   
  );
  
  --CHECK 제약조건에 맞지않는 예 제약조건 위배
  INSERT INTO TABLE_CHECK VALUES ('TEST_ID', '123', '010-1234-5678');
  
  --CHECK 제약조건에 맞지않는 예 제약조건 위배
  INSERT INTO TABLE_CHECK VALUES ('TEST_ID', '1234', '010-1234-5678');
  
  --제약 조건 확인
  SELECT OWNER, CONSTRAINT_NAME , CONSTRAINT_TYPE , TABLE_NAME, R_OWNER , R_CONSTRAINT_NAME 
   FROM USER_CONSTRAINTS
  WHERE TABLE_NAME IN ('TABLE_CHECK')
  
  /* DEFAULT 제약조건 생략 */
  
  --제약 조건 비활성화 활성화 
  --비활성화 : ALTER TABLE 테이블 이름 DISABLE [NOVALIDATE/VALIDATE(선택)] CONSTRAINT 제약조건 이름;
  --활성화 : ALTER TABLE 테이블 이름 ENABLE [NOVALIDATE/VALIDATE(선택)] CONSTRAINT 제약조건 이름;
  
  CREATE TABLE DEPT_CONST (
  
  	  DEPTNO NUMBER(2) CONSTRAINT DEPTCONST_DEPTNO_PK PRIMARY KEY, 
  	  DNAME  VARCHAR2(14) CONSTRAINT DEPTCONST_DNAME_UNQ UNIQUE,
  	  LOC    VARCHAR2(13) CONSTRAINT DEPTCONST_LOC_NN NOT NULL
  );
  
  CREATE TABLE EMP_CONST(
    
     EMPNO NUMBER(4) CONSTRAINT EMPCONST_EMPNO_PK PRIMARY KEY,
     ENAME VARCHAR2(10) CONSTRAINT EMPCONST_ENAME_NN NOT NULL,
     JOB   VARCHAR2(9) , 
     TEL   VARCHAR2(20) CONSTRAINT EMPCONST_TEL_UNQ UNIQUE,
     HIREDATE DATE  ,
     SAL   NUMBER(7,2) CONSTRAINT EMPCONST_SAL_CHK CHECK ((LENGTH(SAL) BETWEEN 1000 AND 9999)) ,
     COMM  NUMBER(7,2) ,
     DEPTNO NUMBER(2) CONSTRAINT EMPCONST_DEPTNO_FK REFERENCES DEPT_CONST (DEPTNO)
  
  );
  
  SELECT TABLE_NAME , CONSTRAINT_NAME, CONSTRAINT_TYPE
    FROM USER_CONSTRAINTS
   WHERE TABLE_NAME IN ('DEPT_CONST', 'EMP_CONST')
   ORDER BY TABLE_NAME, CONSTRAINT_NAME
   ;